// Code generated by goplus from path.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package gjson provides immutable compiled JSON paths and a bounded migration
// facade for github.com/tidwall/gjson. The semantic API distinguishes missing,
// null, malformed, and borrowed values without float64 number coercion.
// Go+ compiled path semantics.
package gjson

import (
	"fmt"
	"strconv"
	"strings"
)

// Type mirrors the stable GJSON result kinds.
type Type int

const (
	Null Type = iota
	False
	Number
	String
	True
	JSON
)

func (t Type) String() string {
	switch t {
	case Null:
		return "Null"
	case False:
		return "False"
	case Number:
		return "Number"
	case String:
		return "String"
	case True:
		return "True"
	case JSON:
		return "JSON"
	default:
		return ""
	}
}

type segment struct {
	text    string
	escaped bool
}

// Path is an immutable parsed path. It is safe for concurrent reuse.
type Path struct {
	source   string
	key      string
	segments []segment
}

// CompilePath parses a tier-1 GJSON path. Dot-separated object components,
// backslash escaping, and numeric array components are supported.
func CompilePath(path string) (*Path, error) {
	if path == "" {
		return &Path{source: path}, nil
	}
	segments := make([]segment, 0, strings.Count(path, ".")+1)
	start, escaped, querySyntax := 0, false, false
	var builder strings.Builder
	for i := 0; i <= len(path); i++ {
		if i == len(path) || path[i] == '.' {
			if i == start && !escaped {
				return nil, fmt.Errorf("gjson: empty path component at byte %d", i)
			}
			text := path[start:i]
			if escaped {
				text = builder.String()
				builder.Reset()
			}
			if querySyntax {
				return nil, fmt.Errorf("gjson: tier-1 query syntax in component %q is unsupported", text)
			}
			segments = append(segments, segment{text: text, escaped: escaped})
			start, escaped, querySyntax = i+1, false, false
			continue
		}
		if path[i] == '\\' {
			if i+1 >= len(path) {
				return nil, fmt.Errorf("gjson: trailing path escape at byte %d", i)
			}
			if !escaped {
				builder.WriteString(path[start:i])
				escaped = true
			}
			i++
			builder.WriteByte(path[i])
			continue
		}
		if strings.ContainsRune("*?#@|![](){}:,\"", rune(path[i])) {
			querySyntax = true
		}
		if escaped {
			builder.WriteByte(path[i])
		}
	}
	var canonical strings.Builder
	for i, part := range segments {
		if i > 0 {
			canonical.WriteByte('.')
		}
		encoded := Escape(part.text)
		if part.escaped && encoded == part.text {
			canonical.WriteByte('\\')
		}
		canonical.WriteString(encoded)
	}
	return &Path{source: path, key: canonical.String(), segments: segments}, nil
}

func MustCompilePath(path string) *Path {
	compiled, err := CompilePath(path)
	if err != nil {
		panic(err)
	}
	return compiled
}
func (p *Path) String() string {
	if p == nil {
		return ""
	}
	return p.source
}
func (p *Path) Len() int {
	if p == nil {
		return 0
	}
	return len(p.segments)
}

// State is the exhaustive semantic outcome discriminator.
type State uint8

const (
	MissingState State = iota
	NullState
	ValueState
	MalformedState
)

// Lookup is a query result. Value is valid only in ValueState, while Err is
// non-nil only in MalformedState.
type Lookup struct {
	state State
	value Borrowed
	err   error
}

func (r Lookup) State() State            { return r.state }
func (r Lookup) Value() (Borrowed, bool) { return r.value, r.state == ValueState }
func (r Lookup) Err() error              { return r.err }

// Borrowed is a zero-copy view into its source JSON string. Keeping Borrowed
// alive keeps the source string alive. It never aliases caller-owned []byte.
type Borrowed struct {
	source                 string
	start, end             int
	kind                   Type
	stringStart, stringEnd int
	escaped                bool
}

func (v Borrowed) Type() Type { return v.kind }
func (v Borrowed) Raw() string {
	if v.start < 0 || v.end < v.start || v.end > len(v.source) {
		return ""
	}
	return v.source[v.start:v.end]
}
func (v Borrowed) IsString() bool { return v.kind == String }
func (v Borrowed) IsNumber() bool { return v.kind == Number }
func (v Borrowed) IsObject() bool {
	return v.kind == JSON && v.start < v.end && v.source[v.start] == '{'
}
func (v Borrowed) IsArray() bool {
	return v.kind == JSON && v.start < v.end && v.source[v.start] == '['
}

// AppendString appends the decoded JSON string without an intermediate
// allocation. The destination controls ownership and reuse.
func (v Borrowed) AppendString(dst []byte) ([]byte, error) {
	if v.kind != String {
		return dst, fmt.Errorf("gjson: value is %s, not string", v.kind)
	}
	if !v.escaped {
		return append(dst, v.source[v.stringStart:v.stringEnd]...), nil
	}
	return appendDecodedString(dst, v.source[v.stringStart:v.stringEnd])
}

func (v Borrowed) StringValue() (string, error) {
	bytes, err := v.AppendString(nil)
	return string(bytes), err
}
func (v Borrowed) Int64() (int64, error) {
	if v.kind != Number {
		return 0, fmt.Errorf("gjson: value is %s, not number", v.kind)
	}
	raw := v.Raw()
	if strings.IndexAny(raw, ".eE") >= 0 {
		return 0, fmt.Errorf("gjson: %q is not an integer", raw)
	}
	value, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("gjson: lossless integer: %w", err)
	}
	return value, nil
}
func (v Borrowed) Float64() (float64, error) {
	if v.kind != Number {
		return 0, fmt.Errorf("gjson: value is %s, not number", v.kind)
	}
	return strconv.ParseFloat(v.Raw(), 64)
}
func (v Borrowed) Bool() (bool, error) {
	if v.kind == True {
		return true, nil
	}
	if v.kind == False {
		return false, nil
	}
	return false, fmt.Errorf("gjson: value is %s, not boolean", v.kind)
}

// Query evaluates a compiled path without allocations.
func (p *Path) Query(json string) Lookup {
	document, err := ParseDocument(json)
	if err != nil {
		return Lookup{state: MalformedState, err: err}
	}
	return document.Query(p)
}
