// Code generated by goplus from schema.gp. DO NOT EDIT.
//goplus:v v0.28.0

package gjson

import "goforge.dev/gpgjson/typed"

// ParseTypedPath is the existential boundary for runtime path strings. The
// schema identity remains in the result index while exhaustive matching
// recovers the requested leaf type.
//
//goplus:dep ParseTypedPath(schema nat, source string, kind typed.ValueKind) typed.PathParse[schema]
func ParseTypedPath(schema int, source string, kind typed.ValueKind) typed.PathParse {
	segments, err := parseTypedSegments(source)
	if err != nil {
		return typed.PathRejected{Error: typed.PathError{Message: err.Error()}}
	}
	switch any(kind).(type) {
	case typed.BooleanKind:
		return typed.PathParsed{Path: typed.SomeBooleanPath{Path: typed.NewPath[bool](schema, segments, kind)}}
	case typed.IntegerKind:
		return typed.PathParsed{Path: typed.SomeIntegerPath{Path: typed.NewPath[int](schema, segments, kind)}}
	case typed.NumberKind:
		return typed.PathParsed{Path: typed.SomeNumberPath{Path: typed.NewPath[typed.NumberText](schema, segments, kind)}}
	case typed.StringKind:
		return typed.PathParsed{Path: typed.SomeStringPath{Path: typed.NewPath[typed.StringView](schema, segments, kind)}}
	case typed.ObjectKind:
		return typed.PathRejected{Error: typed.PathError{Message: "object paths are deferred from typed tier 1"}}
	case typed.ArrayKind:
		return typed.PathRejected{Error: typed.PathError{Message: "array paths are deferred from typed tier 1"}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep BindJSONDocument(schema nat, document Document) typed.TypedDocument[schema, Document]
func BindJSONDocument(schema int, document Document) typed.TypedDocument[Document] {
	return typed.BindDocument(schema, document)
}

//goplus:dep BindCBORDocument(schema nat, document []byte) typed.TypedDocument[schema, []byte]
func BindCBORDocument(schema int, document []byte) typed.TypedDocument[[]byte] {
	owned := append([]byte(nil), document...)
	return typed.BindDocument(schema, owned)
}

//goplus:dep LookupInteger(0 schema nat, path typed.Path[schema, int], document typed.TypedDocument[schema, Document]) typed.SomeLookup[int]
func LookupInteger(path typed.Path[int], document typed.TypedDocument[Document]) typed.SomeLookup[int] {
	return lookupTypedInteger(typed.OpenDocument(path, document), typed.Key(path))
}

//goplus:dep LookupBoolean(0 schema nat, path typed.Path[schema, bool], document typed.TypedDocument[schema, Document]) typed.SomeLookup[bool]
func LookupBoolean(path typed.Path[bool], document typed.TypedDocument[Document]) typed.SomeLookup[bool] {
	return lookupTypedBoolean(typed.OpenDocument(path, document), typed.Key(path))
}

//goplus:dep LookupString(0 schema nat, path typed.Path[schema, typed.StringView], document typed.TypedDocument[schema, Document]) typed.SomeLookup[typed.StringView]
func LookupString(path typed.Path[typed.StringView], document typed.TypedDocument[Document]) typed.SomeLookup[typed.StringView] {
	return lookupTypedString(typed.OpenDocument(path, document), typed.Key(path))
}

// LookupStringInto is the unboxed hot-path eliminator. It retains the same
// schema equality obligation and writes only for ValueState.
//
//goplus:dep LookupStringInto(0 schema nat, path typed.Path[schema, typed.StringView], document typed.TypedDocument[schema, Document], destination *typed.StringView) State
func LookupStringInto(path typed.Path[typed.StringView], document typed.TypedDocument[Document], destination *typed.StringView) State {
	return lookupTypedStringInto(typed.OpenDocument(path, document), typed.Key(path), destination)
}

//goplus:dep LookupNumber(0 schema nat, path typed.Path[schema, typed.NumberText], document typed.TypedDocument[schema, Document]) typed.SomeLookup[typed.NumberText]
func LookupNumber(path typed.Path[typed.NumberText], document typed.TypedDocument[Document]) typed.SomeLookup[typed.NumberText] {
	return lookupTypedNumber(typed.OpenDocument(path, document), typed.Key(path))
}

// LookupCBORInteger is the second-format consumer of Path[S,T]. It preserves
// the same schema index while the format-specific traversal remains outside
// the prospective shared standard abstraction.
//
//goplus:dep LookupCBORInteger(0 schema nat, path typed.Path[schema, int], document typed.TypedDocument[schema, []byte]) typed.SomeLookup[int]
func LookupCBORInteger(path typed.Path[int], document typed.TypedDocument[[]byte]) typed.SomeLookup[int] {
	return lookupCBORInteger(typed.OpenDocument(path, document), typed.Segments(path))
}
