// Code generated by goplus from typed.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package typed is the checked schema/path core for GoForge JSON paths.
package typed

import (
	"strconv"
	"strings"
)

//goplus:enum Segment
type Segment interface{ isSegment() }

//goplus:variant (Segment) Field(Name string)
type Field struct {
	Name string
}

func (Field) isSegment() {}

//goplus:variant (Segment) Index(Position int)
type Index struct {
	Position int
}

func (Index) isSegment() {}

// SegmentCases selects one handler per Segment variant for SegmentFold.
type SegmentCases[R any] struct {
	Field func(Name string) R
	Index func(Position int) R
}

// SegmentFold reduces Segment by one-level case analysis.
func SegmentFold[R any](s Segment, cs SegmentCases[R]) R {
	switch m := any(s).(type) {
	case Field:
		return cs.Field(m.Name)
	case Index:
		return cs.Index(m.Position)
	default:
		panic("goplus: impossible enum value in SegmentFold")
	}
}

// SegmentEqOverrides carries optional per-variant hooks for SegmentEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type SegmentEqOverrides struct {
	Field func(x, y Field) (eq, handled bool)
	Index func(x, y Index) (eq, handled bool)
}

// SegmentEqualWith reports structural equality of a and b under ov.
func SegmentEqualWith(a, b Segment, ov SegmentEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Field:
		y, ok := any(b).(Field)
		if !ok {
			return false
		}
		if ov.Field != nil {
			if eq, handled := ov.Field(x, y); handled {
				return eq
			}
		}
		if x.Name != y.Name {
			return false
		}
		return true
	case Index:
		y, ok := any(b).(Index)
		if !ok {
			return false
		}
		if ov.Index != nil {
			if eq, handled := ov.Index(x, y); handled {
				return eq
			}
		}
		if x.Position != y.Position {
			return false
		}
		return true
	}
	return false
}

// SegmentEqual reports structural equality of a and b.
func SegmentEqual(a, b Segment) bool {
	return SegmentEqualWith(a, b, SegmentEqOverrides{})
}

//goplus:enum ValueKind
type ValueKind interface{ isValueKind() }

//goplus:variant (ValueKind) BooleanKind()
type BooleanKind struct{}

func (BooleanKind) isValueKind() {}

//goplus:variant (ValueKind) IntegerKind()
type IntegerKind struct{}

func (IntegerKind) isValueKind() {}

//goplus:variant (ValueKind) NumberKind()
type NumberKind struct{}

func (NumberKind) isValueKind() {}

//goplus:variant (ValueKind) StringKind()
type StringKind struct{}

func (StringKind) isValueKind() {}

//goplus:variant (ValueKind) ObjectKind()
type ObjectKind struct{}

func (ObjectKind) isValueKind() {}

//goplus:variant (ValueKind) ArrayKind()
type ArrayKind struct{}

func (ArrayKind) isValueKind() {}

// ValueKindCases selects one handler per ValueKind variant for ValueKindFold.
type ValueKindCases[R any] struct {
	BooleanKind func() R
	IntegerKind func() R
	NumberKind  func() R
	StringKind  func() R
	ObjectKind  func() R
	ArrayKind   func() R
}

// ValueKindFold reduces ValueKind by one-level case analysis.
func ValueKindFold[R any](v ValueKind, cs ValueKindCases[R]) R {
	switch any(v).(type) {
	case BooleanKind:
		return cs.BooleanKind()
	case IntegerKind:
		return cs.IntegerKind()
	case NumberKind:
		return cs.NumberKind()
	case StringKind:
		return cs.StringKind()
	case ObjectKind:
		return cs.ObjectKind()
	case ArrayKind:
		return cs.ArrayKind()
	default:
		panic("goplus: impossible enum value in ValueKindFold")
	}
}

// ValueKindEqOverrides carries optional per-variant hooks for ValueKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ValueKindEqOverrides struct {
	BooleanKind func(x, y BooleanKind) (eq, handled bool)
	IntegerKind func(x, y IntegerKind) (eq, handled bool)
	NumberKind  func(x, y NumberKind) (eq, handled bool)
	StringKind  func(x, y StringKind) (eq, handled bool)
	ObjectKind  func(x, y ObjectKind) (eq, handled bool)
	ArrayKind   func(x, y ArrayKind) (eq, handled bool)
}

// ValueKindEqualWith reports structural equality of a and b under ov.
func ValueKindEqualWith(a, b ValueKind, ov ValueKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case BooleanKind:
		y, ok := any(b).(BooleanKind)
		if !ok {
			return false
		}
		if ov.BooleanKind != nil {
			if eq, handled := ov.BooleanKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case IntegerKind:
		y, ok := any(b).(IntegerKind)
		if !ok {
			return false
		}
		if ov.IntegerKind != nil {
			if eq, handled := ov.IntegerKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case NumberKind:
		y, ok := any(b).(NumberKind)
		if !ok {
			return false
		}
		if ov.NumberKind != nil {
			if eq, handled := ov.NumberKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case StringKind:
		y, ok := any(b).(StringKind)
		if !ok {
			return false
		}
		if ov.StringKind != nil {
			if eq, handled := ov.StringKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ObjectKind:
		y, ok := any(b).(ObjectKind)
		if !ok {
			return false
		}
		if ov.ObjectKind != nil {
			if eq, handled := ov.ObjectKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ArrayKind:
		y, ok := any(b).(ArrayKind)
		if !ok {
			return false
		}
		if ov.ArrayKind != nil {
			if eq, handled := ov.ArrayKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ValueKindEqual reports structural equality of a and b.
func ValueKindEqual(a, b ValueKind) bool {
	return ValueKindEqualWith(a, b, ValueKindEqOverrides{})
}

// NumberText retains the exact JSON decimal spelling. Conversion to a lossy
// floating representation is deliberately outside the checked core.
type NumberText struct{ Raw string }
type StringView struct {
	Raw     string
	Content string
	Escaped bool
}

// Path[S,T] ties a path result T to schema identity S. The constructor is
// sealed so unrelated schema paths cannot be forged in Go+.
//
//goplus:enum Path[S nat, T any]
//goplus:derive off
type Path[T any] interface{ isPath(T) }

//goplus:variant (Path[T]) pathValue(Schema int, Segments []Segment, Key string, Kind ValueKind) Path[S, T]
type pathValue[T any] struct {
	schema   int
	segments []Segment
	key      string
	kind     ValueKind
}

func (pathValue[T]) isPath(T) {}

// TypedDocument[S,D] binds a format-specific immutable document D to schema S.
//
//goplus:enum TypedDocument[S nat, D any]
//goplus:derive off
type TypedDocument[D any] interface{ isTypedDocument(D) }

//goplus:variant (TypedDocument[D]) documentValue(Schema int, Payload D) TypedDocument[S, D]
type documentValue[D any] struct {
	schema  int
	payload D
}

func (documentValue[D]) isTypedDocument(D) {}

type PathError struct{ Message string }

func (e PathError) Error() string { return e.Message }

// Lookup[T,p] indexes the four exhaustive lookup states. The finite
// SomeLookup boundary hides p until exhaustive matching recovers it.
//
//goplus:enum Lookup[T any, p nat]
type Lookup[T any] interface{ isLookup(T) }

//goplus:variant (Lookup[T]) Missing() Lookup[T, 0]
type Missing[T any] struct{}

func (Missing[T]) isLookup(T) {}

//goplus:variant (Lookup[T]) Null() Lookup[T, 1]
type Null[T any] struct{}

func (Null[T]) isLookup(T) {}

//goplus:variant (Lookup[T]) Present(Value T) Lookup[T, 2]
type Present[T any] struct {
	Value T
}

func (Present[T]) isLookup(T) {}

//goplus:variant (Lookup[T]) Malformed(Error PathError) Lookup[T, 3]
type Malformed[T any] struct {
	Error PathError
}

func (Malformed[T]) isLookup(T) {}

// LookupCases selects one handler per Lookup variant for LookupFold.
type LookupCases[T any, R any] struct {
	Missing   func() R
	Null      func() R
	Present   func(Value T) R
	Malformed func(Error PathError) R
}

// LookupFold reduces Lookup[T] by one-level case analysis.
func LookupFold[T any, R any](l Lookup[T], cs LookupCases[T, R]) R {
	switch m := any(l).(type) {
	case Missing[T]:
		return cs.Missing()
	case Null[T]:
		return cs.Null()
	case Present[T]:
		return cs.Present(m.Value)
	case Malformed[T]:
		return cs.Malformed(m.Error)
	default:
		panic("goplus: impossible enum value in LookupFold")
	}
}

//goplus:enum SomeLookup[T any]
type SomeLookup[T any] interface{ isSomeLookup(T) }

//goplus:variant (SomeLookup[T]) MissingLookup(Result Lookup[T, 0])
type MissingLookup[T any] struct {
	Result Lookup[T]
}

func (MissingLookup[T]) isSomeLookup(T) {}

//goplus:variant (SomeLookup[T]) NullLookup(Result Lookup[T, 1])
type NullLookup[T any] struct {
	Result Lookup[T]
}

func (NullLookup[T]) isSomeLookup(T) {}

//goplus:variant (SomeLookup[T]) PresentLookup(Result Lookup[T, 2])
type PresentLookup[T any] struct {
	Result Lookup[T]
}

func (PresentLookup[T]) isSomeLookup(T) {}

//goplus:variant (SomeLookup[T]) MalformedLookup(Result Lookup[T, 3])
type MalformedLookup[T any] struct {
	Result Lookup[T]
}

func (MalformedLookup[T]) isSomeLookup(T) {}

// SomeLookupCases selects one handler per SomeLookup variant for SomeLookupFold.
type SomeLookupCases[T any, R any] struct {
	MissingLookup   func(Result Lookup[T]) R
	NullLookup      func(Result Lookup[T]) R
	PresentLookup   func(Result Lookup[T]) R
	MalformedLookup func(Result Lookup[T]) R
}

// SomeLookupFold reduces SomeLookup[T] by one-level case analysis.
func SomeLookupFold[T any, R any](s SomeLookup[T], cs SomeLookupCases[T, R]) R {
	switch m := any(s).(type) {
	case MissingLookup[T]:
		return cs.MissingLookup(m.Result)
	case NullLookup[T]:
		return cs.NullLookup(m.Result)
	case PresentLookup[T]:
		return cs.PresentLookup(m.Result)
	case MalformedLookup[T]:
		return cs.MalformedLookup(m.Result)
	default:
		panic("goplus: impossible enum value in SomeLookupFold")
	}
}

// SomePath[S] hides the leaf result type T while retaining the document schema
// index. Matching a variant recovers the concrete Path[S,T].
//
//goplus:enum SomePath[S nat]
type SomePath interface{ isSomePath() }

//goplus:variant (SomePath) SomeBooleanPath(Path Path[S, bool])
type SomeBooleanPath struct {
	Path Path[bool]
}

func (SomeBooleanPath) isSomePath() {}

//goplus:variant (SomePath) SomeIntegerPath(Path Path[S, int])
type SomeIntegerPath struct {
	Path Path[int]
}

func (SomeIntegerPath) isSomePath() {}

//goplus:variant (SomePath) SomeNumberPath(Path Path[S, NumberText])
type SomeNumberPath struct {
	Path Path[NumberText]
}

func (SomeNumberPath) isSomePath() {}

//goplus:variant (SomePath) SomeStringPath(Path Path[S, StringView])
type SomeStringPath struct {
	Path Path[StringView]
}

func (SomeStringPath) isSomePath() {}

// SomePathCases selects one handler per SomePath variant for SomePathFold.
type SomePathCases[R any] struct {
	SomeBooleanPath func(Path Path[bool]) R
	SomeIntegerPath func(Path Path[int]) R
	SomeNumberPath  func(Path Path[NumberText]) R
	SomeStringPath  func(Path Path[StringView]) R
}

// SomePathFold reduces SomePath by one-level case analysis.
func SomePathFold[R any](s SomePath, cs SomePathCases[R]) R {
	switch m := any(s).(type) {
	case SomeBooleanPath:
		return cs.SomeBooleanPath(m.Path)
	case SomeIntegerPath:
		return cs.SomeIntegerPath(m.Path)
	case SomeNumberPath:
		return cs.SomeNumberPath(m.Path)
	case SomeStringPath:
		return cs.SomeStringPath(m.Path)
	default:
		panic("goplus: impossible enum value in SomePathFold")
	}
}

//goplus:enum PathParse[S nat]
type PathParse interface{ isPathParse() }

//goplus:variant (PathParse) PathParsed(Path SomePath[S])
type PathParsed struct {
	Path SomePath
}

func (PathParsed) isPathParse() {}

//goplus:variant (PathParse) PathRejected(Error PathError)
type PathRejected struct {
	Error PathError
}

func (PathRejected) isPathParse() {}

// PathParseCases selects one handler per PathParse variant for PathParseFold.
type PathParseCases[R any] struct {
	PathParsed   func(Path SomePath) R
	PathRejected func(Error PathError) R
}

// PathParseFold reduces PathParse by one-level case analysis.
func PathParseFold[R any](p PathParse, cs PathParseCases[R]) R {
	switch m := any(p).(type) {
	case PathParsed:
		return cs.PathParsed(m.Path)
	case PathRejected:
		return cs.PathRejected(m.Error)
	default:
		panic("goplus: impossible enum value in PathParseFold")
	}
}

// PresentValue requires p=2 statically; missing, null, and malformed values
// cannot reach this function in Go+.
//
//goplus:dep PresentValue[T any](value Lookup[T, 2]) T
func PresentValue[T any](value Lookup[T]) T {
	if _, ok := any(value).(Missing[T]); ok {
		panic("goplus: PresentValue: value with index 2 cannot be Missing")
	}
	if _, ok := any(value).(Null[T]); ok {
		panic("goplus: PresentValue: value with index 2 cannot be Null")
	}
	if _, ok := any(value).(Malformed[T]); ok {
		panic("goplus: PresentValue: value with index 2 cannot be Malformed")
	}
	switch __gp_m0 := any(value).(type) {
	case Present[T]:
		result := __gp_m0.Value
		return result
	default:
		panic("goplus: impossible enum value in match")
	}
}

// NewPath is the checked construction boundary. Schema IDs survive erasure for
// defensive ordinary-Go boundary checks.
//
//goplus:dep NewPath[T any](schema nat, segments []Segment, kind ValueKind) Path[schema, T]
func NewPath[T any](schema int, segments []Segment, kind ValueKind) Path[T] {
	if schema < 0 {
		panic("gjson/typed: negative schema")
	}
	owned := append([]Segment(nil), segments...)
	return pathValue[T]{schema: int(schema), segments: owned, key: pathKey(owned), kind: kind}
}

//goplus:dep BindDocument[D any](schema nat, document D) TypedDocument[schema, D]
func BindDocument[D any](schema int, document D) TypedDocument[D] {
	if schema < 0 {
		panic("gjson/typed: negative schema")
	}
	return documentValue[D]{schema: int(schema), payload: document}
}

//goplus:dep DocumentValue[D any](0 schema nat, document TypedDocument[schema, D]) D
func DocumentValue[D any](document TypedDocument[D]) D {
	switch __gp_m1 := any(document).(type) {
	case documentValue[D]:
		payload := __gp_m1.payload
		return payload
	default:
		panic("goplus: impossible enum value in match")
	}
}

// OpenDocument validates the retained schema witnesses after Go erasure.
//
//goplus:dep OpenDocument[T any, D any](0 schema nat, path Path[schema, T], document TypedDocument[schema, D]) D
func OpenDocument[T any, D any](path Path[T], document TypedDocument[D]) D {
	switch __gp_m2 := any(path).(type) {
	case pathValue[T]:
		pathSchema := __gp_m2.schema

		switch __gp_m3 := any(document).(type) {
		case documentValue[D]:
			documentSchema := __gp_m3.schema
			payload := __gp_m3.payload

			if pathSchema != documentSchema {
				panic("gjson/typed: erased path/document schema mismatch")
			}
			return payload
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Segments[T any](0 schema nat, path Path[schema, T]) []Segment
func Segments[T any](path Path[T]) []Segment {
	switch __gp_m4 := any(path).(type) {
	case pathValue[T]:
		segments := __gp_m4.segments
		return append([]Segment(nil), segments...)
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Kind[T any](0 schema nat, path Path[schema, T]) ValueKind
func Kind[T any](path Path[T]) ValueKind {
	switch __gp_m5 := any(path).(type) {
	case pathValue[T]:
		kind := __gp_m5.kind
		return kind
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:dep Key[T any](0 schema nat, path Path[schema, T]) string
func Key[T any](path Path[T]) string {
	switch __gp_m6 := any(path).(type) {
	case pathValue[T]:
		key := __gp_m6.key
		return key
	default:
		panic("goplus: impossible enum value in match")
	}
}

// Compose preserves the document schema index while appending an immutable
// suffix. The result type is determined by the suffix path.
//
//goplus:dep Compose[A any, B any](0 schema nat, prefix Path[schema, A], suffix Path[schema, B]) Path[schema, B]
func Compose[A any, B any](prefix Path[A], suffix Path[B]) Path[B] {
	switch __gp_m7 := any(prefix).(type) {
	case pathValue[A]:
		prefixSchema := __gp_m7.schema
		left := __gp_m7.segments

		switch __gp_m8 := any(suffix).(type) {
		case pathValue[B]:
			suffixSchema := __gp_m8.schema
			right := __gp_m8.segments
			kind := __gp_m8.kind

			if prefixSchema != suffixSchema {
				panic("gjson/typed: erased schema mismatch")
			}
			segments := append(append([]Segment(nil), left...), right...)
			return pathValue[B]{schema: prefixSchema, segments: segments, key: pathKey(segments), kind: kind}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func pathKey(segments []Segment) string {
	var builder strings.Builder
	for i, segment := range segments {
		if i > 0 {
			builder.WriteByte('.')
		}
		switch __gp_m9 := any(segment).(type) {
		case Field:
			name := __gp_m9.Name

			for j := 0; j < len(name); j++ {
				if name[j] == '.' || name[j] == '\\' {
					builder.WriteByte('\\')
				}
				builder.WriteByte(name[j])
			}
		case Index:
			position := __gp_m9.Position
			builder.WriteString(strconv.Itoa(position))
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	return builder.String()
}
